#!/usr/bin/env python3

# pass commdand line items into main cli-client
# initialize basic items

import os
import sys
import argparse

try:
    import googleapiclient
    import google_auth_oauthlib
    import google.auth
except:
    print("Failed to import Google Drive API libraries.")
    print("Please check the dependencies list.")
    raise

try:
    import peewee
except:
    print("Failed to import peewee library.")
    print("Please check the dependencies list.")
    raise

from gdclient.gdclient import PyGDClient
from gdclient import log

parser = argparse.ArgumentParser(description='Python GDrive CLI')
parser.add_argument('settings', type=str, help='path to settings.json')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true')
parser.add_argument('-f', '--full', dest='full', action='store_true',
                    help='run full recursive scan')

args = parser.parse_args()

if args.verbose:
    log.set_max_level(log.DEBUG)
else:
    log.set_max_level(log.INFO)

gdcli = PyGDClient(args.settings)
gdcli.run(args.full)
