#!/usr/bin/env python3

# pass commdand line items into main cli-client
# check for basic sanity and requirements

import os
import sys
import json

try:
    import googleapiclient
    import google_auth_oauthlib
    import google.auth
except:
    print("Failed to import Google Drive API libraries.")
    raise

try:
	import peewee
except:
    print("Failed to import peewee library.")
    raise


if len(sys.argv) < 2:
	print("\n\tUsage: %s <settings.json>" %sys.argv[0])
	print("\tNo settings.json specified.\n")
	exit(1)

from gdclient.gdclient import PyGDClient
gdcli = PyGDClient(sys.argv[1])
gdcli.run()

